#!/bin/zsh

local current_brightness
local max_brightness

if [[ $1 == "" ]]; then
	current_brightness="$(cat /sys/class/backlight/intel_backlight/brightness)"
	max_brightness="$(cat /sys/class/backlight/intel_backlight/max_brightness)"
	echo "Current brightness = $current_brightness"
	echo "Max brightness = $max_brightness"
fi
if [[ -n $1 ]]; then
	sudo tee /sys/class/backlight/intel_backlight/brightness <<< $1
fi
